### ISSUE TITLE
program

### ISSUE THREAD

**Issue by mengluffy** [sergivalverde/cnn-ms-lesion-segmentation#2]
Dear Dr. Sergi Valverde, I download your program, my environment is ubuntu 16.04, but I use jupyter notebook cell example_1.pynb always error. I also install requirements.txt , can your help me. Thank you very much.

**Comment by sergivalverde** [comment]
Hi @mengluffy . I litle more information of the problem would help to know the type of error you have :)

**Comment by mengluffy** [comment]
I change set，than a warning. And program not do








------------------ 原始邮件 ------------------
发件人: "Sergi Valverde";<notifications@github.com>;
发送时间: 2017年9月5日(星期二) 下午3:03
收件人: "sergivalverde/cnn-ms-lesion-segmentation"<cnn-ms-lesion-segmentation@noreply.github.com>; 
抄送: "奥特曼"<1278257502@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sergivalverde/cnn-ms-lesion-segmentation] program (#2)




Hi @mengluffy . I litle more information of the problem would help to know the type of error you have :)
