### ISSUE TITLE
I have a problem with filetypes

### ISSUE THREAD

**Issue by Setthanun** [sergivalverde/cnn-ms-lesion-segmentation#4]
Hi @sergivalverde

I want to get data to use to run the program. I use data from MICCAI2008 (filetype *.nhdr). But the filetype does not match the specified code (filetype *.nii.gz). Where can I get it? 
If you know, please answer me.

Thank you

**Comment by sergivalverde** [comment]
hej @Setthanun!

you have to convert the images from nrrd format to nifti by yourself.  In the challenge webpage there are instructions on how to do it:

http://www.ia.unc.edu/MSseg/faq.html

However, I was converting them using the [cmtk](https://www.nitrc.org/projects/cmtk/) toolbox. One of the  tools inside is `convertx` which do this pretty well.  Look to `cmtk convertx --help` for more info.
