### ISSUE TITLE
requirements.txt errors

### ISSUE THREAD

**Issue by FrancyGalassi** [sergivalverde/cnn-ms-lesion-segmentation#6]
Hello,

I was not able to simply run pip install on the requirements file because some versions were not found. Maybe they have been updated or changed and thus not available anymore?

I have now latest version for Lasagne, etc. However, as you may expect, some issues come out. It says that theano.sandobox... gives error. I'm not really capable to find out where and what to change to make it work. Any idea what to do? Thank you very much in advance.

**Comment by sergivalverde** [comment]
Can you elaborate a little bit more on the output returned by pip?

Thanks,
s

**Comment by FrancyGalassi** [comment]
It is ok now, it was a matter of finding the right versions and compatibilities for upgraded libraries.
